version: "3.8"

services:
  educamais-chatbot:
    build: .
    container_name: educamais-chatbot
    ports:
      - "8502:8501"  # 8501 é interno (Streamlit), 8502 é externo (VPS)
    volumes:
      - ./logs:/app/logs
      - ./logs/errors:/app/logs/errors
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=production
    restart: always
