name: CI - Code Quality and Security

on:
  push:
  pull_request:
  workflow_dispatch:  # Permite execução manual através da interface do GitHub

jobs:
  lint-and-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint black ruff mypy bandit

      - name: Run Ruff
        run: ruff check **/*.py

      - name: Run Black (check only)
        run: black --check .

      - name: Run Pylint
        run: pylint streamlit_app.py loader.py || true

      - name: Run Mypy
        run: mypy . || true

      - name: Run Bandit
        run: bandit -r . -x venv
