name: CD - Deploy VPS

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
  workflow_dispatch:  # Permite execução manual através da interface do GitHub

jobs:
  deploy:
    name: Deploy VPS via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build da imagem Docker (clean build)
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/langchain-quickstart:latest .

      - name: Push da imagem para o Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/langchain-quickstart:latest

      - name: Acesso SSH e deploy na VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_SSH }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/langchain-quickstart
            git pull origin main
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/langchain-quickstart:latest
            docker compose down
            docker compose up -d
